apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hph
  name: frontend-prod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: quachuoiscontainer/hph_fe
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: hph
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
