apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hph
  name: frontend-uat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: quachuoiscontainer/hph_fe
          ports:
            - containerPort: 80